/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param a Alpha parameter of the Beta distribution
 * @param b Beta parameter of the Beta distribution
 */


data class BetaDistribution (

    /* Alpha parameter of the Beta distribution */
    @Json(name = "a")
    val a: kotlin.Double,

    /* Beta parameter of the Beta distribution */
    @Json(name = "b")
    val b: kotlin.Double

) {


}

