/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param model 
 * @param revision 
 */


data class ConfigurationResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "model")
    val model: kotlin.Any?,

    @Json(name = "revision")
    val revision: kotlin.Int

) {


}

