/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A structured JSON error response
 *
 * @param error A machine-readable error code
 * @param message A human-readable error message
 * @param details 
 */


data class ErrorResponse (

    /* A machine-readable error code */
    @Json(name = "error")
    val error: kotlin.String,

    /* A human-readable error message */
    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "details")
    val details: kotlin.Any? = null

) {


}

