/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import ivk.skill.api.models.MatchMetadata
import ivk.skill.api.models.PlayerSession
import ivk.skill.api.models.TeamInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param playerSessions A list of all player sessions for one single match. There can be multiple sessions for the same player.
 * @param teams A list of teams and their metadata
 * @param matchEndTs Time the match ended (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this.
 * @param matchId Unique match identifier
 * @param matchStartTs Time the match started (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this.
 * @param metadata Several properties to provide more context about the match
 */


data class MatchResultRequest (

    /* A list of all player sessions for one single match. There can be multiple sessions for the same player. */
    @Json(name = "player_sessions")
    val playerSessions: kotlin.collections.List<PlayerSession>,

    /* A list of teams and their metadata */
    @Json(name = "teams")
    val teams: kotlin.collections.List<TeamInfo>,

    /* Time the match ended (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this. */
    @Json(name = "match_end_ts")
    val matchEndTs: java.time.OffsetDateTime? = null,

    /* Unique match identifier */
    @Json(name = "match_id")
    val matchId: kotlin.String? = null,

    /* Time the match started (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this. */
    @Json(name = "match_start_ts")
    val matchStartTs: java.time.OffsetDateTime? = null,

    /* Several properties to provide more context about the match */
    @Json(name = "metadata")
    val metadata: MatchMetadata? = null

) {


}

