/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param gameMode The gamemode for this match.
 * @param season The season the match was played in
 */


data class MatchMetadata (

    /* The gamemode for this match. */
    @Json(name = "game_mode")
    val gameMode: kotlin.String? = null,

    /* The season the match was played in */
    @Json(name = "season")
    val season: kotlin.Int? = null

) {


}

