/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import ivk.skill.api.models.MatchInfo
import ivk.skill.api.models.PlayerResult
import ivk.skill.api.models.TeamResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param matchInfo Match metadata
 * @param players List of skill rating updates per player. One per player.
 * @param teams List of team update result
 */


data class MatchResultResponse (

    /* Match metadata */
    @Json(name = "match_info")
    val matchInfo: MatchInfo,

    /* List of skill rating updates per player. One per player. */
    @Json(name = "players")
    val players: kotlin.collections.List<PlayerResult>,

    /* List of team update result */
    @Json(name = "teams")
    val teams: kotlin.collections.List<TeamResult>

) {


}

