/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param duration Total duration of the match
 * @param maxTs The maximum timestamp for the match
 * @param meanMmr The mean MMR of all players in the match
 * @param minTs The minimum timestamp for the match
 * @param mmrDeviation MMR deviation for this match (useful to determine match quality)
 * @param partyCount Total parties that were part of this match
 * @param playerCount Total amount of unique players in this match
 * @param teamCount Total teams that were part of this match
 * @param matchId Passthrough match_id if provided
 */


data class MatchInfo (

    /* Total duration of the match */
    @Json(name = "duration")
    val duration: kotlin.Double,

    /* The maximum timestamp for the match */
    @Json(name = "max_ts")
    val maxTs: kotlin.Double,

    /* The mean MMR of all players in the match */
    @Json(name = "mean_mmr")
    val meanMmr: kotlin.Double,

    /* The minimum timestamp for the match */
    @Json(name = "min_ts")
    val minTs: kotlin.Double,

    /* MMR deviation for this match (useful to determine match quality) */
    @Json(name = "mmr_deviation")
    val mmrDeviation: kotlin.Double,

    /* Total parties that were part of this match */
    @Json(name = "party_count")
    val partyCount: kotlin.Int,

    /* Total amount of unique players in this match */
    @Json(name = "player_count")
    val playerCount: kotlin.Int,

    /* Total teams that were part of this match */
    @Json(name = "team_count")
    val teamCount: kotlin.Int,

    /* Passthrough match_id if provided */
    @Json(name = "match_id")
    val matchId: kotlin.String? = null

) {


}

