/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Start & end timestamp
 *
 * @param end A timestamp of when this playersession ended.
 * @param start A timestamp of when this playersession started.
 */


data class PlayerSessionTimestamps (

    /* A timestamp of when this playersession ended. */
    @Json(name = "end")
    val end: kotlin.Double,

    /* A timestamp of when this playersession started. */
    @Json(name = "start")
    val start: kotlin.Double

) {


}

