/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import ivk.skill.api.models.PlayerSessionTimestamps

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param playerId The unique identifier of the player
 * @param playerScore The player score in this match Default: 0 It's up to the game to determine this value. The only requirement is that a higher score is better than a lower score. This value only matters if player performance is configured to have non-zero weight.
 * @param isBot Used to flag this session as a Bot session
 * @param partyId Local identifier of the player's party. If set, should be unique per party per match. Default behavior is to treat each player as their own party, so party_id can be omitted for games that don't support parties.
 * @param perfBeta Override for rating uncertainty (advanced option) Default behavior is to use values generated by model
 * @param playerScoreStart The player's score at the start of this session (advanced option) Default behavior is to inherit player_score from the end of the previous session (recommended) Used for score-per-minute normalization in cases where players can rejoin matches e.g. set this to 0 if player scores are reset on rejoin
 * @param priorGamesPlayed The previous number of games the player has played (ever, or just this season).
 * @param priorMmr The MMR of the player at the start of the match. A number between 0 and 1 Default: default_mmr specified in the MMR configuration
 * @param priorMomentum Incoming momentum (**not used in most models**) For models with experimental anti-smurfing features or rating acceleration Essentially rolling-average win rate
 * @param sessionTimestamps 
 * @param teamId Local identifier of the player's team. If set must match one of the teams provided in the [[MatchResult]]. Default behavior is to treat each player as their own team, so team_id can be omitted for 1v1 or free-for-all modes.
 */


data class PlayerSession (

    /* The unique identifier of the player */
    @Json(name = "player_id")
    val playerId: kotlin.String,

    /* The player score in this match Default: 0 It's up to the game to determine this value. The only requirement is that a higher score is better than a lower score. This value only matters if player performance is configured to have non-zero weight. */
    @Json(name = "player_score")
    val playerScore: kotlin.Double,

    /* Used to flag this session as a Bot session */
    @Json(name = "is_bot")
    val isBot: kotlin.Boolean? = null,

    /* Local identifier of the player's party. If set, should be unique per party per match. Default behavior is to treat each player as their own party, so party_id can be omitted for games that don't support parties. */
    @Json(name = "party_id")
    val partyId: kotlin.String? = null,

    /* Override for rating uncertainty (advanced option) Default behavior is to use values generated by model */
    @Json(name = "perf_beta")
    val perfBeta: kotlin.Double? = null,

    /* The player's score at the start of this session (advanced option) Default behavior is to inherit player_score from the end of the previous session (recommended) Used for score-per-minute normalization in cases where players can rejoin matches e.g. set this to 0 if player scores are reset on rejoin */
    @Json(name = "player_score_start")
    val playerScoreStart: kotlin.Double? = null,

    /* The previous number of games the player has played (ever, or just this season). */
    @Json(name = "prior_games_played")
    val priorGamesPlayed: kotlin.Long? = null,

    /* The MMR of the player at the start of the match. A number between 0 and 1 Default: default_mmr specified in the MMR configuration */
    @Json(name = "prior_mmr")
    val priorMmr: kotlin.Double? = null,

    /* Incoming momentum (**not used in most models**) For models with experimental anti-smurfing features or rating acceleration Essentially rolling-average win rate */
    @Json(name = "prior_momentum")
    val priorMomentum: kotlin.Double? = null,

    @Json(name = "session_timestamps")
    val sessionTimestamps: PlayerSessionTimestamps? = null,

    /* Local identifier of the player's team. If set must match one of the teams provided in the [[MatchResult]]. Default behavior is to treat each player as their own team, so team_id can be omitted for 1v1 or free-for-all modes. */
    @Json(name = "team_id")
    val teamId: kotlin.String? = null

) {


}

