/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import ivk.skill.api.models.PreMatchPlayerResultExtended
import ivk.skill.api.models.PriorPlayerStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param extended Extended player update information
 * @param playerId The unique identifier of the player (passed through)
 * @param playerIdx Internal player index
 * @param post Updated player stats after this match
 * @param prior Player stats from the start of this match
 */


data class PreMatchPlayerResult (

    /* Extended player update information */
    @Json(name = "extended")
    val extended: PreMatchPlayerResultExtended,

    /* The unique identifier of the player (passed through) */
    @Json(name = "player_id")
    val playerId: kotlin.String,

    /* Internal player index */
    @Json(name = "player_idx")
    val playerIdx: kotlin.Int,

    /* Updated player stats after this match */
    @Json(name = "post")
    val post: PriorPlayerStats,

    /* Player stats from the start of this match */
    @Json(name = "prior")
    val prior: PriorPlayerStats

) {


}

