/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamId Unique identifier for the team (within the context of this match)
 */


data class PreMatchTeamInfo (

    /* Unique identifier for the team (within the context of this match) */
    @Json(name = "team_id")
    val teamId: kotlin.String

) {


}

