/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import ivk.skill.api.models.MatchMetadata
import ivk.skill.api.models.PreMatchPlayerSession
import ivk.skill.api.models.PreMatchTeamInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param playerSessions A list of all player sessions for one single match. There can be multiple sessions for a single player.
 * @param teams A list of teams and their metadata
 * @param matchId Unique match identifier
 * @param metadata Several properties to provide more context about the match
 */


data class PreMatchRequest (

    /* A list of all player sessions for one single match. There can be multiple sessions for a single player. */
    @Json(name = "player_sessions")
    val playerSessions: kotlin.collections.List<PreMatchPlayerSession>,

    /* A list of teams and their metadata */
    @Json(name = "teams")
    val teams: kotlin.collections.List<PreMatchTeamInfo>,

    /* Unique match identifier */
    @Json(name = "match_id")
    val matchId: kotlin.String? = null,

    /* Several properties to provide more context about the match */
    @Json(name = "metadata")
    val metadata: MatchMetadata? = null

) {


}

