/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param gamesPlayed Amount of games played
 * @param mmr The player MMR
 * @param momentum Rolling-average win rate (**if used by model**)
 */


data class PriorPlayerStats (

    /* Amount of games played */
    @Json(name = "games_played")
    val gamesPlayed: kotlin.Long,

    /* The player MMR */
    @Json(name = "mmr")
    val mmr: kotlin.Double,

    /* Rolling-average win rate (**if used by model**) */
    @Json(name = "momentum")
    val momentum: kotlin.Double

) {


}

