/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamId Unique identifier for the team (within the context of this match)
 * @param teamScore The team score
 */


data class TeamInfo (

    /* Unique identifier for the team (within the context of this match) */
    @Json(name = "team_id")
    val teamId: kotlin.String,

    /* The team score */
    @Json(name = "team_score")
    val teamScore: kotlin.Double

) {


}

