/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.apis

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.apis.SkillApi
import ivk.skill.api.models.ConfigurationResponse
import ivk.skill.api.models.MatchResultRequest
import ivk.skill.api.models.MatchResultResponse
import ivk.skill.api.models.PreMatchRequest
import ivk.skill.api.models.PreMatchResponse

class SkillApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SkillApi
        //val apiInstance = SkillApi()

        // to test getConfiguration
        should("test getConfiguration") {
            // uncomment below to test getConfiguration
            //val modelId : kotlin.String = abc123 // kotlin.String | ID of the skill rating model
            //val result : ConfigurationResponse = apiInstance.getConfiguration(modelId)
            //result shouldBe ("TODO")
        }

        // to test postMatchResult
        should("test postMatchResult") {
            // uncomment below to test postMatchResult
            //val modelId : kotlin.String = abc123 // kotlin.String | ID of the skill rating model
            //val environment : kotlin.String = prod // kotlin.String | Environment
            //val matchResultRequest : MatchResultRequest = {"match_id":"unique_id_1234","player_sessions":[{"player_id":"player_1","player_score":200,"prior_games_played":80,"prior_mmr":0.5},{"player_id":"player_2","player_score":250,"prior_games_played":70,"prior_mmr":0.4}],"teams":[]} // MatchResultRequest | 
            //val result : MatchResultResponse = apiInstance.postMatchResult(modelId, environment, matchResultRequest)
            //result shouldBe ("TODO")
        }

        // to test postPreMatch
        should("test postPreMatch") {
            // uncomment below to test postPreMatch
            //val modelId : kotlin.String = abc123 // kotlin.String | ID of the skill rating model
            //val environment : kotlin.String = prod // kotlin.String | Environment
            //val preMatchRequest : PreMatchRequest = {"match_id":"unique_id_1234","player_sessions":[{"player_id":"player_1","prior_games_played":80,"prior_mmr":0.5},{"player_id":"player_2","prior_games_played":70,"prior_mmr":0.4}],"teams":[]} // PreMatchRequest | 
            //val result : PreMatchResponse = apiInstance.postPreMatch(modelId, environment, preMatchRequest)
            //result shouldBe ("TODO")
        }

    }
}
