/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ivk.skill.api.models.BetaDistribution

class BetaDistributionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BetaDistribution
        //val modelInstance = BetaDistribution()

        // to test the property `a` - Alpha parameter of the Beta distribution
        should("test a") {
            // uncomment below to test the property
            //modelInstance.a shouldBe ("TODO")
        }

        // to test the property `b` - Beta parameter of the Beta distribution
        should("test b") {
            // uncomment below to test the property
            //modelInstance.b shouldBe ("TODO")
        }

    }
}
