/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.MatchResultResponse
import ivk.skill.api.models.MatchInfo
import ivk.skill.api.models.PlayerResult
import ivk.skill.api.models.TeamResult

class MatchResultResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchResultResponse
        //val modelInstance = MatchResultResponse()

        // to test the property `matchInfo` - Match metadata
        should("test matchInfo") {
            // uncomment below to test the property
            //modelInstance.matchInfo shouldBe ("TODO")
        }

        // to test the property `players` - List of skill rating updates per player. One per player.
        should("test players") {
            // uncomment below to test the property
            //modelInstance.players shouldBe ("TODO")
        }

        // to test the property `teams` - List of team update result
        should("test teams") {
            // uncomment below to test the property
            //modelInstance.teams shouldBe ("TODO")
        }

    }
}
