/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.MatchInfo

class MatchInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchInfo
        //val modelInstance = MatchInfo()

        // to test the property `duration` - Total duration of the match
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `maxTs` - The maximum timestamp for the match
        should("test maxTs") {
            // uncomment below to test the property
            //modelInstance.maxTs shouldBe ("TODO")
        }

        // to test the property `meanMmr` - The mean MMR of all players in the match
        should("test meanMmr") {
            // uncomment below to test the property
            //modelInstance.meanMmr shouldBe ("TODO")
        }

        // to test the property `minTs` - The minimum timestamp for the match
        should("test minTs") {
            // uncomment below to test the property
            //modelInstance.minTs shouldBe ("TODO")
        }

        // to test the property `mmrDeviation` - MMR deviation for this match (useful to determine match quality)
        should("test mmrDeviation") {
            // uncomment below to test the property
            //modelInstance.mmrDeviation shouldBe ("TODO")
        }

        // to test the property `partyCount` - Total parties that were part of this match
        should("test partyCount") {
            // uncomment below to test the property
            //modelInstance.partyCount shouldBe ("TODO")
        }

        // to test the property `playerCount` - Total amount of unique players in this match
        should("test playerCount") {
            // uncomment below to test the property
            //modelInstance.playerCount shouldBe ("TODO")
        }

        // to test the property `teamCount` - Total teams that were part of this match
        should("test teamCount") {
            // uncomment below to test the property
            //modelInstance.teamCount shouldBe ("TODO")
        }

        // to test the property `matchId` - Passthrough match_id if provided
        should("test matchId") {
            // uncomment below to test the property
            //modelInstance.matchId shouldBe ("TODO")
        }

    }
}
