/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.MatchMetadata

class MatchMetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchMetadata
        //val modelInstance = MatchMetadata()

        // to test the property `gameMode` - The gamemode for this match.
        should("test gameMode") {
            // uncomment below to test the property
            //modelInstance.gameMode shouldBe ("TODO")
        }

        // to test the property `season` - The season the match was played in
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

    }
}
