/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.MatchResultRequest
import ivk.skill.api.models.MatchMetadata
import ivk.skill.api.models.PlayerSession
import ivk.skill.api.models.TeamInfo

class MatchResultRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchResultRequest
        //val modelInstance = MatchResultRequest()

        // to test the property `playerSessions` - A list of all player sessions for one single match. There can be multiple sessions for the same player.
        should("test playerSessions") {
            // uncomment below to test the property
            //modelInstance.playerSessions shouldBe ("TODO")
        }

        // to test the property `teams` - A list of teams and their metadata
        should("test teams") {
            // uncomment below to test the property
            //modelInstance.teams shouldBe ("TODO")
        }

        // to test the property `matchEndTs` - Time the match ended (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this.
        should("test matchEndTs") {
            // uncomment below to test the property
            //modelInstance.matchEndTs shouldBe ("TODO")
        }

        // to test the property `matchId` - Unique match identifier
        should("test matchId") {
            // uncomment below to test the property
            //modelInstance.matchId shouldBe ("TODO")
        }

        // to test the property `matchStartTs` - Time the match started (ISO 8601 UTC timestamp). Apart from backfilling historical data or simulations, you probably don't need to pass this.
        should("test matchStartTs") {
            // uncomment below to test the property
            //modelInstance.matchStartTs shouldBe ("TODO")
        }

        // to test the property `metadata` - Several properties to provide more context about the match
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
