/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ivk.skill.api.models.PlayerSessionTimestamps

class PlayerSessionTimestampsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerSessionTimestamps
        //val modelInstance = PlayerSessionTimestamps()

        // to test the property `end` - A timestamp of when this playersession ended.
        should("test end") {
            // uncomment below to test the property
            //modelInstance.end shouldBe ("TODO")
        }

        // to test the property `start` - A timestamp of when this playersession started.
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

    }
}
