/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ivk.skill.api.models.PlayerSession
import ivk.skill.api.models.PlayerSessionTimestamps

class PlayerSessionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerSession
        //val modelInstance = PlayerSession()

        // to test the property `playerId` - The unique identifier of the player
        should("test playerId") {
            // uncomment below to test the property
            //modelInstance.playerId shouldBe ("TODO")
        }

        // to test the property `playerScore` - The player score in this match Default: 0 It's up to the game to determine this value. The only requirement is that a higher score is better than a lower score. This value only matters if player performance is configured to have non-zero weight.
        should("test playerScore") {
            // uncomment below to test the property
            //modelInstance.playerScore shouldBe ("TODO")
        }

        // to test the property `isBot` - Used to flag this session as a Bot session
        should("test isBot") {
            // uncomment below to test the property
            //modelInstance.isBot shouldBe ("TODO")
        }

        // to test the property `partyId` - Local identifier of the player's party. If set, should be unique per party per match. Default behavior is to treat each player as their own party, so party_id can be omitted for games that don't support parties.
        should("test partyId") {
            // uncomment below to test the property
            //modelInstance.partyId shouldBe ("TODO")
        }

        // to test the property `perfBeta` - Override for rating uncertainty (advanced option) Default behavior is to use values generated by model
        should("test perfBeta") {
            // uncomment below to test the property
            //modelInstance.perfBeta shouldBe ("TODO")
        }

        // to test the property `playerScoreStart` - The player's score at the start of this session (advanced option) Default behavior is to inherit player_score from the end of the previous session (recommended) Used for score-per-minute normalization in cases where players can rejoin matches e.g. set this to 0 if player scores are reset on rejoin
        should("test playerScoreStart") {
            // uncomment below to test the property
            //modelInstance.playerScoreStart shouldBe ("TODO")
        }

        // to test the property `priorGamesPlayed` - The previous number of games the player has played (ever, or just this season).
        should("test priorGamesPlayed") {
            // uncomment below to test the property
            //modelInstance.priorGamesPlayed shouldBe ("TODO")
        }

        // to test the property `priorMmr` - The MMR of the player at the start of the match. A number between 0 and 1 Default: default_mmr specified in the MMR configuration
        should("test priorMmr") {
            // uncomment below to test the property
            //modelInstance.priorMmr shouldBe ("TODO")
        }

        // to test the property `priorMomentum` - Incoming momentum (**not used in most models**) For models with experimental anti-smurfing features or rating acceleration Essentially rolling-average win rate
        should("test priorMomentum") {
            // uncomment below to test the property
            //modelInstance.priorMomentum shouldBe ("TODO")
        }

        // to test the property `sessionTimestamps`
        should("test sessionTimestamps") {
            // uncomment below to test the property
            //modelInstance.sessionTimestamps shouldBe ("TODO")
        }

        // to test the property `teamId` - Local identifier of the player's team. If set must match one of the teams provided in the [[MatchResult]]. Default behavior is to treat each player as their own team, so team_id can be omitted for 1v1 or free-for-all modes.
        should("test teamId") {
            // uncomment below to test the property
            //modelInstance.teamId shouldBe ("TODO")
        }

    }
}
