/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.PlayerUpdateExtended
import ivk.skill.api.models.BetaDistribution

class PlayerUpdateExtendedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerUpdateExtended
        //val modelInstance = PlayerUpdateExtended()

        // to test the property `alpha` - All the teams the player was a part of during this match Calculated scale factor for uncertainty and step sizes typically = 1.0 outside of placement
        should("test alpha") {
            // uncomment below to test the property
            //modelInstance.alpha shouldBe ("TODO")
        }

        // to test the property `isBot` - Passthrough from request
        should("test isBot") {
            // uncomment below to test the property
            //modelInstance.isBot shouldBe ("TODO")
        }

        // to test the property `maxTs`
        should("test maxTs") {
            // uncomment below to test the property
            //modelInstance.maxTs shouldBe ("TODO")
        }

        // to test the property `minTs`
        should("test minTs") {
            // uncomment below to test the property
            //modelInstance.minTs shouldBe ("TODO")
        }

        // to test the property `mmrDelta` - Change in MMR after this match
        should("test mmrDelta") {
            // uncomment below to test the property
            //modelInstance.mmrDelta shouldBe ("TODO")
        }

        // to test the property `playerExpected` - Expected individual outcome for the player (0-1) potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs
        should("test playerExpected") {
            // uncomment below to test the property
            //modelInstance.playerExpected shouldBe ("TODO")
        }

        // to test the property `playerOutcome` - Actual individual outcome for the player (0-1)
        should("test playerOutcome") {
            // uncomment below to test the property
            //modelInstance.playerOutcome shouldBe ("TODO")
        }

        // to test the property `playerScoreRate` - Player score per time unit
        should("test playerScoreRate") {
            // uncomment below to test the property
            //modelInstance.playerScoreRate shouldBe ("TODO")
        }

        // to test the property `playerWeight` - How much weight individual outcome has to influence MMR
        should("test playerWeight") {
            // uncomment below to test the property
            //modelInstance.playerWeight shouldBe ("TODO")
        }

        // to test the property `residual` - Difference between actual and expected outcomes (prediction error)
        should("test residual") {
            // uncomment below to test the property
            //modelInstance.residual shouldBe ("TODO")
        }

        // to test the property `sessionCount` - Total number of sessions for this player during this match
        should("test sessionCount") {
            // uncomment below to test the property
            //modelInstance.sessionCount shouldBe ("TODO")
        }

        // to test the property `teamCount` - The amount of teams the player was a part of during this match
        should("test teamCount") {
            // uncomment below to test the property
            //modelInstance.teamCount shouldBe ("TODO")
        }

        // to test the property `teamExpected` - Weighted average of expected outcomes of all teams this player was a member of
        should("test teamExpected") {
            // uncomment below to test the property
            //modelInstance.teamExpected shouldBe ("TODO")
        }

        // to test the property `teamOutcome` - Weighted average of actual outcomes of all teams this player was a memeber of
        should("test teamOutcome") {
            // uncomment below to test the property
            //modelInstance.teamOutcome shouldBe ("TODO")
        }

        // to test the property `teamWeight` - How much weight team outcome has to influences MMR
        should("test teamWeight") {
            // uncomment below to test the property
            //modelInstance.teamWeight shouldBe ("TODO")
        }

        // to test the property `unifiedExpected` - Combined team and individual expected outcomes
        should("test unifiedExpected") {
            // uncomment below to test the property
            //modelInstance.unifiedExpected shouldBe ("TODO")
        }

        // to test the property `unifiedExpectedDist` - The Beta distribution of expected outcomes Encodes how much certainty we have about the unified expected outcome
        should("test unifiedExpectedDist") {
            // uncomment below to test the property
            //modelInstance.unifiedExpectedDist shouldBe ("TODO")
        }

        // to test the property `unifiedOutcome` - Combined team and individual actual outcomes
        should("test unifiedOutcome") {
            // uncomment below to test the property
            //modelInstance.unifiedOutcome shouldBe ("TODO")
        }

    }
}
