/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.PlayerResult
import ivk.skill.api.models.PlayerUpdateExtended
import ivk.skill.api.models.PriorPlayerStats

class PlayerResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerResult
        //val modelInstance = PlayerResult()

        // to test the property `extended` - Extended player update information
        should("test extended") {
            // uncomment below to test the property
            //modelInstance.extended shouldBe ("TODO")
        }

        // to test the property `playerId` - The unique identifier of the player (passed through)
        should("test playerId") {
            // uncomment below to test the property
            //modelInstance.playerId shouldBe ("TODO")
        }

        // to test the property `playerIdx` - Zero-indexed player index
        should("test playerIdx") {
            // uncomment below to test the property
            //modelInstance.playerIdx shouldBe ("TODO")
        }

        // to test the property `post` - Updated player stats after this match
        should("test post") {
            // uncomment below to test the property
            //modelInstance.post shouldBe ("TODO")
        }

        // to test the property `prior` - Player stats from the start of this match
        should("test prior") {
            // uncomment below to test the property
            //modelInstance.prior shouldBe ("TODO")
        }

    }
}
