/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ivk.skill.api.models.PreMatchRequest
import ivk.skill.api.models.MatchMetadata
import ivk.skill.api.models.PreMatchPlayerSession
import ivk.skill.api.models.PreMatchTeamInfo

class PreMatchRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PreMatchRequest
        //val modelInstance = PreMatchRequest()

        // to test the property `playerSessions` - A list of all player sessions for one single match. There can be multiple sessions for a single player.
        should("test playerSessions") {
            // uncomment below to test the property
            //modelInstance.playerSessions shouldBe ("TODO")
        }

        // to test the property `teams` - A list of teams and their metadata
        should("test teams") {
            // uncomment below to test the property
            //modelInstance.teams shouldBe ("TODO")
        }

        // to test the property `matchId` - Unique match identifier
        should("test matchId") {
            // uncomment below to test the property
            //modelInstance.matchId shouldBe ("TODO")
        }

        // to test the property `metadata` - Several properties to provide more context about the match
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
