/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ivk.skill.api.models.PreMatchTeamInfo

class PreMatchTeamInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PreMatchTeamInfo
        //val modelInstance = PreMatchTeamInfo()

        // to test the property `teamId` - Unique identifier for the team (within the context of this match)
        should("test teamId") {
            // uncomment below to test the property
            //modelInstance.teamId shouldBe ("TODO")
        }

    }
}
