/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ivk.skill.api.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import ivk.skill.api.models.PriorPlayerStats

class PriorPlayerStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriorPlayerStats
        //val modelInstance = PriorPlayerStats()

        // to test the property `gamesPlayed` - Amount of games played
        should("test gamesPlayed") {
            // uncomment below to test the property
            //modelInstance.gamesPlayed shouldBe ("TODO")
        }

        // to test the property `mmr` - The player MMR
        should("test mmr") {
            // uncomment below to test the property
            //modelInstance.mmr shouldBe ("TODO")
        }

        // to test the property `momentum` - Rolling-average win rate (**if used by model**)
        should("test momentum") {
            // uncomment below to test the property
            //modelInstance.momentum shouldBe ("TODO")
        }

    }
}
