/*
 * This source file was generated by the Gradle 'init' task
 */
package ivk.skill.example

import ivk.skill.api.models.*
import ivk.skill.sdk.SkillSdk
import kotlinx.coroutines.runBlocking

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println("Running IVK Skill sample Kotlin App")

    val apiKey = ""
    val modelId = "default"

    val sdk = SkillSdk.builder().apiKey(apiKey).baseUrl("http://localhost:8080").build()

    val matchResultRequest =
            MatchResultRequest(
                    matchId = "match_id_123",
                    playerSessions =
                            listOf(
                                    PlayerSession(
                                            playerId = "player1",
                                            playerScore = 10.0,
                                            priorMmr = 0.1,
                                            teamId = "team_a"
                                    ),
                                    PlayerSession(
                                            playerId = "player2",
                                            playerScore = 15.0,
                                            priorMmr = 0.2,
                                            teamId = "team_b"
                                    )
                            ),
                    teams =
                            listOf(
                                    TeamInfo(
                                            teamId = "team_a",
                                            teamScore = 100.0,
                                    ),
                                    TeamInfo(
                                            teamId = "team_b",
                                            teamScore = 150.0,
                                    )
                            )
            )

    runBlocking {
        try {
            val response = sdk.postMatchResult(modelId, matchResultRequest)
            println(response)
        } catch (e: Exception) {
            println("Error posting match result: ${e.message}")
            e.printStackTrace()
        } finally {
            sdk.close()
        }
    }
}
